// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern ADC_HandleTypeDef hadc12;
extern ADC_HandleTypeDef hadc11;
extern ADC_HandleTypeDef hadc10;
extern ADC_HandleTypeDef hadc9;
extern ADC_HandleTypeDef hadc8;
extern ADC_HandleTypeDef hadc7;
extern ADC_HandleTypeDef hadc6;
extern ADC_HandleTypeDef hadc5;
extern ADC_HandleTypeDef hadc4;
extern ADC_HandleTypeDef hadc3;
extern ADC_HandleTypeDef hadc2;
extern ADC_HandleTypeDef hadc1;


void MX_ADC12_Init(void);
void MX_ADC11_Init(void);
void MX_ADC10_Init(void);
void MX_ADC9_Init(void);
void MX_ADC8_Init(void);
void MX_ADC7_Init(void);
void MX_ADC6_Init(void);
void MX_ADC5_Init(void);
void MX_ADC4_Init(void);
void MX_ADC3_Init(void);
void MX_ADC2_Init(void);
void MX_ADC1_Init(void);


#ifdef __cplusplus
}
#endif
