// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern CAN_HandleTypeDef hcan2;
extern CAN_HandleTypeDef hcan1;


void MX_CAN2_Init(void);
void MX_CAN1_Init(void);


#ifdef __cplusplus
}
#endif
