// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern COMP_HandleTypeDef hcomp7;
extern COMP_HandleTypeDef hcomp6;
extern COMP_HandleTypeDef hcomp5;
extern COMP_HandleTypeDef hcomp4;
extern COMP_HandleTypeDef hcomp3;
extern COMP_HandleTypeDef hcomp2;
extern COMP_HandleTypeDef hcomp1;


void MX_COMP7_Init(void);
void MX_COMP6_Init(void);
void MX_COMP5_Init(void);
void MX_COMP4_Init(void);
void MX_COMP3_Init(void);
void MX_COMP2_Init(void);
void MX_COMP1_Init(void);


#ifdef __cplusplus
}
#endif
