// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern DAC_HandleTypeDef hdac2;
extern DAC_HandleTypeDef hdac1;


void MX_DAC2_Init(void);
void MX_DAC1_Init(void);


#ifdef __cplusplus
}
#endif
