// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern DCMI_HandleTypeDef hdcmi;


void MX_DCMI_Init(void);


#ifdef __cplusplus
}
#endif
