// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern DFSDM_HandleTypeDef hdfsdm;


void MX_DFSDM_Init(void);


#ifdef __cplusplus
}
#endif
