// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern ETH_HandleTypeDef heth;


void MX_ETH_Init(void);


#ifdef __cplusplus
}
#endif
