// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern FMC_HandleTypeDef hfmc;


void MX_FMC_Init(void);


#ifdef __cplusplus
}
#endif
