// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern FSMC_HandleTypeDef hfsmc;


void MX_FSMC_Init(void);


#ifdef __cplusplus
}
#endif
