// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern HRTIM_HandleTypeDef hhrtim;


void MX_HRTIM_Init(void);


#ifdef __cplusplus
}
#endif
