// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern I2C_HandleTypeDef hi2c3;
extern I2C_HandleTypeDef hi2c2;
extern I2C_HandleTypeDef hi2c1;


void MX_I2C3_Init(void);
void MX_I2C2_Init(void);
void MX_I2C1_Init(void);


#ifdef __cplusplus
}
#endif
