// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern LPTIM_HandleTypeDef hlptim2;
extern LPTIM_HandleTypeDef hlptim1;


void MX_LPTIM2_Init(void);
void MX_LPTIM1_Init(void);


#ifdef __cplusplus
}
#endif
