// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern OPAMP_HandleTypeDef hopamp4;
extern OPAMP_HandleTypeDef hopamp3;
extern OPAMP_HandleTypeDef hopamp2;
extern OPAMP_HandleTypeDef hopamp1;


void MX_OPAMP4_Init(void);
void MX_OPAMP3_Init(void);
void MX_OPAMP2_Init(void);
void MX_OPAMP1_Init(void);


#ifdef __cplusplus
}
#endif
