// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern QUADSPI_HandleTypeDef hquadspi;


void MX_QUADSPI_Init(void);


#ifdef __cplusplus
}
#endif
