// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern RTC_HandleTypeDef hrtc;


void MX_RTC_Init(void);


#ifdef __cplusplus
}
#endif
