// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern SAI_HandleTypeDef hsai2;
extern SAI_HandleTypeDef hsai1;


void MX_SAI2_Init(void);
void MX_SAI1_Init(void);


#ifdef __cplusplus
}
#endif
