// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"

#ifdef __cplusplus
 extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "stm32f3xx_hal.h"

extern SDADC_HandleTypeDef hsdadc1;
extern SDADC_HandleTypeDef hsdadc2;
extern SDADC_HandleTypeDef hsdadc3;

void MX_SDADC1_Init(void);
void MX_SDADC2_Init(void);
void MX_SDADC3_Init(void);

#ifdef __cplusplus
}
#endif
