// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern SDIO_HandleTypeDef hsdio;


void MX_SDIO_Init(void);


#ifdef __cplusplus
}
#endif
