// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern SDMMC_HandleTypeDef hsdmmc;


void MX_SDMMC_Init(void);


#ifdef __cplusplus
}
#endif
