// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern SPDIFRX_HandleTypeDef hspdifrx;


void MX_SPDIFRX_Init(void);


#ifdef __cplusplus
}
#endif
