// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern SPI_HandleTypeDef hspi6;
extern SPI_HandleTypeDef hspi5;
extern SPI_HandleTypeDef hspi4;
extern SPI_HandleTypeDef hspi3;
extern SPI_HandleTypeDef hspi2;
extern SPI_HandleTypeDef hspi1;


void MX_SPI6_Init(void);
void MX_SPI5_Init(void);
void MX_SPI4_Init(void);
void MX_SPI3_Init(void);
void MX_SPI2_Init(void);
void MX_SPI1_Init(void);


#ifdef __cplusplus
}
#endif
