// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern SWPMI_HandleTypeDef hswpmi;


void MX_SWPMI_Init(void);


#ifdef __cplusplus
}
#endif
