// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern TIM_HandleTypeDef htim14;
extern TIM_HandleTypeDef htim13;
extern TIM_HandleTypeDef htim12;
extern TIM_HandleTypeDef htim11;
extern TIM_HandleTypeDef htim10;
extern TIM_HandleTypeDef htim9;
extern TIM_HandleTypeDef htim8;
extern TIM_HandleTypeDef htim7;
extern TIM_HandleTypeDef htim6;
extern TIM_HandleTypeDef htim5;
extern TIM_HandleTypeDef htim4;
extern TIM_HandleTypeDef htim3;
extern TIM_HandleTypeDef htim2;
extern TIM_HandleTypeDef htim1;


void MX_TIM14_Init(void);
void MX_TIM13_Init(void);
void MX_TIM12_Init(void);
void MX_TIM11_Init(void);
void MX_TIM10_Init(void);
void MX_TIM9_Init(void);
void MX_TIM8_Init(void);
void MX_TIM7_Init(void);
void MX_TIM6_Init(void);
void MX_TIM5_Init(void);
void MX_TIM4_Init(void);
void MX_TIM3_Init(void);
void MX_TIM2_Init(void);
void MX_TIM1_Init(void);


#ifdef __cplusplus
}
#endif
