// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern UART_HandleTypeDef huart4;
extern UART_HandleTypeDef huart3;
extern UART_HandleTypeDef huart2;
extern UART_HandleTypeDef huart1;


void MX_UART4_Init(void);
void MX_UART3_Init(void);
void MX_UART2_Init(void);
void MX_UART1_Init(void);


#ifdef __cplusplus
}
#endif
