// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"

#ifdef __cplusplus
extern "C" {
#endif

/* USER CODE BEGIN Private defines */

/* USER CODE END Private defines */
extern UART_HandleTypeDef huart8;
extern UART_HandleTypeDef huart7;
extern UART_HandleTypeDef huart6;
extern UART_HandleTypeDef huart5;
extern UART_HandleTypeDef huart4;
extern UART_HandleTypeDef huart3;
extern UART_HandleTypeDef huart2;
extern UART_HandleTypeDef huart1;

void MX_USART8_UART_Init(void);
void MX_USART7_UART_Init(void);
void MX_USART6_UART_Init(void);
void MX_USART5_UART_Init(void);
void MX_USART4_UART_Init(void);
void MX_USART3_UART_Init(void);
void MX_USART2_UART_Init(void);
void MX_USART1_UART_Init(void);

#ifdef __cplusplus
}
#endif
