// file generated by tvc-lisp Juin 2015
#pragma once

#include "stm32.h"


#ifdef __cplusplus
extern "C" {
#endif
extern USART_HandleTypeDef husart8;
extern USART_HandleTypeDef husart7;
extern USART_HandleTypeDef husart6;
extern USART_HandleTypeDef husart5;
extern USART_HandleTypeDef husart4;
extern USART_HandleTypeDef husart3;
extern USART_HandleTypeDef husart2;
extern USART_HandleTypeDef husart1;


void MX_USART8_Init(void);
void MX_USART7_Init(void);
void MX_USART6_Init(void);
void MX_USART5_Init(void);
void MX_USART4_Init(void);
void MX_USART3_Init(void);
void MX_USART2_Init(void);
void MX_USART1_Init(void);


#ifdef __cplusplus
}
#endif
